[package]
name = "Harbr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde_json = "1.0.132"
tokio = {version = "1.41.1", features = ["full"]}
warp = "0.3.7"
